listen : ":9111"     # Port for the http Server to listen on 
probetime: 120  # How often Probes are executed in Seconds
# Hosts to display an avg ping of 3 PingProbes
pingtest: 
- "1.1.1.1"
- "1.0.0.1"
- "8.8.8.8"
- "8.8.4.4"
