listen : ":9111"     # Port for the http Server to listen on 
probetime: 120  # How often Probes are executed in Seconds
# Hosts to display an avg ping of 3 PingProbes
avgpingprobes: 
- "1.1.1.1"
- "1.0.0.1"
- "8.8.8.8"
- "8.8.4.4"
# Send a Ping  to test if they are online
onlinepingprobes: 
- "golem.de"
- "test.de"
# Send an HTTP Get-Request to test if the hosts are online, needs https:// or http://
onlinehttpprobes:
- "http://golem.de"
- "http://google.de"